#!/bin/sh

set -e

records="$(khard)"
query="$(khard list -F name | awk '(NR>2)' | sed "s/\s*$//" | dmenu -i)"
field="$(echo -e "phone\nemail" | dmenu -i)"
cmd="$(echo "khard list -F $field $query" | tr -d "(),")"
result="$(echo $cmd | sh)"
copy="$(echo "$result" | tail -n 1 | awk '{print $(NF)}')"
echo $copy | xclip -selection clipboard
echo $copy
