#!/bin/sh

set -e

query="$(khard | awk '{print $2 $3}' | tr "," " " | dmenu -i)"
result="$(khard $query)"
selecton="$(echo -e "phone\nemail" | dmenu -i)"

case "$selection" in
  "phone") copy="$(echo $result | egrep -o "\+([0-9]|\s)*")" ;;
  "email") copy="$(echo $result | egrep -o "\S*@\S*")" ;;
esac

echo $copy | xclip -selection clipboard
exit 0
